ALTER TABLE `watchlist` ADD `exchange` VARCHAR(30) NULL DEFAULT NULL AFTER `note`, ADD `sector` VARCHAR(255) NULL DEFAULT NULL AFTER `exchange`;

UPDATE watchlist SET sector="Information Technology", exchange="NASDAQ" WHERE ticker = "AAPL";
UPDATE watchlist SET sector="Health Care", exchange="NYSE" WHERE ticker = "ABBV";
UPDATE watchlist SET sector="Health Care", exchange="NYSE" WHERE ticker = "ABT";
UPDATE watchlist SET sector="Information Technology", exchange="NYSE" WHERE ticker = "ACN";
UPDATE watchlist SET sector="Health Care", exchange="NYSE" WHERE ticker = "AGN";
UPDATE watchlist SET sector="Financials", exchange="NYSE" WHERE ticker = "AIG";
UPDATE watchlist SET sector="Financials", exchange="NYSE" WHERE ticker = "ALL";
UPDATE watchlist SET sector="Health Care", exchange="NASDAQ" WHERE ticker = "AMGN";
UPDATE watchlist SET sector="Consumer Discretionary", exchange="NASDAQ" WHERE ticker = "AMZN";
UPDATE watchlist SET sector="Financials", exchange="NYSE" WHERE ticker = "AXP";
UPDATE watchlist SET sector="Industrials", exchange="NYSE" WHERE ticker = "BA";
UPDATE watchlist SET sector="Financials", exchange="NYSE" WHERE ticker = "BAC";
UPDATE watchlist SET sector="Health Care", exchange="NASDAQ" WHERE ticker = "BIIB";
UPDATE watchlist SET sector="Financials", exchange="NYSE" WHERE ticker = "BK";
UPDATE watchlist SET sector="Financials", exchange="NYSE" WHERE ticker = "BLK";
UPDATE watchlist SET sector="Health Care", exchange="NYSE" WHERE ticker = "BMY";
UPDATE watchlist SET sector="Financials", exchange="NYSE" WHERE ticker = "C";
UPDATE watchlist SET sector="Industrials", exchange="NYSE" WHERE ticker = "CAT";
UPDATE watchlist SET sector="Health Care", exchange="NASDAQ" WHERE ticker = "CELG";
UPDATE watchlist SET sector="Consumer Staples", exchange="NYSE" WHERE ticker = "CL";
UPDATE watchlist SET sector="Consumer Discretionary", exchange="NASDAQ" WHERE ticker = "CMCSA";
UPDATE watchlist SET sector="Financials", exchange="NYSE" WHERE ticker = "COF";
UPDATE watchlist SET sector="Energy", exchange="NYSE" WHERE ticker = "COP";
UPDATE watchlist SET sector="Consumer Staples", exchange="NASDAQ" WHERE ticker = "COST";
UPDATE watchlist SET sector="Information Technology", exchange="NASDAQ" WHERE ticker = "CSCO";
UPDATE watchlist SET sector="Consumer Staples", exchange="NYSE" WHERE ticker = "CVS";
UPDATE watchlist SET sector="Energy", exchange="NYSE" WHERE ticker = "CVX";
UPDATE watchlist SET sector="Materials", exchange="NYSE" WHERE ticker = "DD";
UPDATE watchlist SET sector="Health Care", exchange="NYSE" WHERE ticker = "DHR";
UPDATE watchlist SET sector="Consumer Discretionary", exchange="NYSE" WHERE ticker = "DIS";
UPDATE watchlist SET sector="Materials", exchange="NYSE" WHERE ticker = "DOW";
UPDATE watchlist SET sector="Utilities", exchange="NYSE" WHERE ticker = "DUK";
UPDATE watchlist SET sector="Industrials", exchange="NYSE" WHERE ticker = "EMR";
UPDATE watchlist SET sector="Utilities", exchange="NYSE" WHERE ticker = "EXC";
UPDATE watchlist SET sector="Consumer Discretionary", exchange="NYSE" WHERE ticker = "F";
UPDATE watchlist SET sector="Information Technology", exchange="NASDAQ" WHERE ticker = "FB";
UPDATE watchlist SET sector="Industrials", exchange="NYSE" WHERE ticker = "FDX";
UPDATE watchlist SET sector="Consumer Discretionary", exchange="NASDAQ" WHERE ticker = "FOXA";
UPDATE watchlist SET sector="Industrials", exchange="NYSE" WHERE ticker = "GD";
UPDATE watchlist SET sector="Industrials", exchange="NYSE" WHERE ticker = "GE";
UPDATE watchlist SET sector="Health Care", exchange="NASDAQ" WHERE ticker = "GILD";
UPDATE watchlist SET sector="Consumer Discretionary", exchange="NYSE" WHERE ticker = "GM";
UPDATE watchlist SET sector="Information Technology", exchange="NASDAQ" WHERE ticker = "GOOG";
UPDATE watchlist SET sector="Financials", exchange="NYSE" WHERE ticker = "GS";
UPDATE watchlist SET sector="Energy", exchange="NYSE" WHERE ticker = "HAL";
UPDATE watchlist SET sector="Consumer Discretionary", exchange="NYSE" WHERE ticker = "HD";
UPDATE watchlist SET sector="Industrials", exchange="NYSE" WHERE ticker = "HON";
UPDATE watchlist SET sector="Information Technology", exchange="NYSE" WHERE ticker = "IBM";
UPDATE watchlist SET sector="Information Technology", exchange="NASDAQ" WHERE ticker = "INTC";
UPDATE watchlist SET sector="Health Care", exchange="NYSE" WHERE ticker = "JNJ";
UPDATE watchlist SET sector="Financials", exchange="NYSE" WHERE ticker = "JPM";
UPDATE watchlist SET sector="Consumer Staples", exchange="NASDAQ" WHERE ticker = "KHC";
UPDATE watchlist SET sector="Energy", exchange="NYSE" WHERE ticker = "KMI";
UPDATE watchlist SET sector="Consumer Staples", exchange="NYSE" WHERE ticker = "KO";
UPDATE watchlist SET sector="Health Care", exchange="NYSE" WHERE ticker = "LLY";
UPDATE watchlist SET sector="Industrials", exchange="NYSE" WHERE ticker = "LMT";
UPDATE watchlist SET sector="Consumer Discretionary", exchange="NYSE" WHERE ticker = "LOW";
UPDATE watchlist SET sector="Information Technology", exchange="NYSE" WHERE ticker = "MA";
UPDATE watchlist SET sector="Consumer Discretionary", exchange="NYSE" WHERE ticker = "MCD";
UPDATE watchlist SET sector="Consumer Staples", exchange="NASDAQ" WHERE ticker = "MDLZ";
UPDATE watchlist SET sector="Health Care", exchange="NYSE" WHERE ticker = "MDT";
UPDATE watchlist SET sector="Financials", exchange="NYSE" WHERE ticker = "MET";
UPDATE watchlist SET sector="Industrials", exchange="NYSE" WHERE ticker = "MMM";
UPDATE watchlist SET sector="Consumer Staples", exchange="NYSE" WHERE ticker = "MO";
UPDATE watchlist SET sector="Materials", exchange="NYSE" WHERE ticker = "MON";
UPDATE watchlist SET sector="Health Care", exchange="NYSE" WHERE ticker = "MRK";
UPDATE watchlist SET sector="Financials", exchange="NYSE" WHERE ticker = "MS";
UPDATE watchlist SET sector="Information Technology", exchange="NASDAQ" WHERE ticker = "MSFT";
UPDATE watchlist SET sector="Utilities", exchange="NYSE" WHERE ticker = "NEE";
UPDATE watchlist SET sector="Consumer Discretionary", exchange="NYSE" WHERE ticker = "NKE";
UPDATE watchlist SET sector="Information Technology", exchange="NYSE" WHERE ticker = "ORCL";
UPDATE watchlist SET sector="Energy", exchange="NYSE" WHERE ticker = "OXY";
UPDATE watchlist SET sector="Consumer Discretionary", exchange="NASDAQ" WHERE ticker = "PCLN";
UPDATE watchlist SET sector="Consumer Staples", exchange="NYSE" WHERE ticker = "PEP";
UPDATE watchlist SET sector="Health Care", exchange="NYSE" WHERE ticker = "PFE";
UPDATE watchlist SET sector="Consumer Staples", exchange="NYSE" WHERE ticker = "PG";
UPDATE watchlist SET sector="Consumer Staples", exchange="NYSE" WHERE ticker = "PM";
UPDATE watchlist SET sector="Information Technology", exchange="NASDAQ" WHERE ticker = "PYPL";
UPDATE watchlist SET sector="Information Technology", exchange="NASDAQ" WHERE ticker = "QCOM";
UPDATE watchlist SET sector="Industrials", exchange="NYSE" WHERE ticker = "RTN";
UPDATE watchlist SET sector="Consumer Discretionary", exchange="NASDAQ" WHERE ticker = "SBUX";
UPDATE watchlist SET sector="Energy", exchange="NYSE" WHERE ticker = "SLB";
UPDATE watchlist SET sector="Utilities", exchange="NYSE" WHERE ticker = "SO";
UPDATE watchlist SET sector="Real Estate", exchange="NYSE" WHERE ticker = "SPG";
UPDATE watchlist SET sector="Telecommunications", exchange="NYSE" WHERE ticker = "T";
UPDATE watchlist SET sector="Consumer Discretionary", exchange="NYSE" WHERE ticker = "TGT";
UPDATE watchlist SET sector="Consumer Discretionary", exchange="NYSE" WHERE ticker = "TWX";
UPDATE watchlist SET sector="Information Technology", exchange="NASDAQ" WHERE ticker = "TXN";
UPDATE watchlist SET sector="Health Care", exchange="NYSE" WHERE ticker = "UNH";
UPDATE watchlist SET sector="Industrials", exchange="NYSE" WHERE ticker = "UNP";
UPDATE watchlist SET sector="Industrials", exchange="NYSE" WHERE ticker = "UPS";
UPDATE watchlist SET sector="Financials", exchange="NYSE" WHERE ticker = "USB";
UPDATE watchlist SET sector="Industrials", exchange="NYSE" WHERE ticker = "UTX";
UPDATE watchlist SET sector="Information Technology", exchange="NYSE" WHERE ticker = "V";
UPDATE watchlist SET sector="Telecommunications", exchange="NYSE" WHERE ticker = "VZ";
UPDATE watchlist SET sector="Consumer Staples", exchange="NASDAQ" WHERE ticker = "WBA";
UPDATE watchlist SET sector="Financials", exchange="NYSE" WHERE ticker = "WFC";
UPDATE watchlist SET sector="Consumer Staples", exchange="NYSE" WHERE ticker = "WMT";
UPDATE watchlist SET sector="Energy", exchange="NYSE" WHERE ticker = "XOM";