-- new watchlist of S&P100 stocks


INSERT INTO `watchlist` (`id`, `ticker`, `name`, `active`, `note`) VALUES
(3, 'ABT', 'Abbott Laboratories', 1, ''),
(4, 'ACN', 'Accenture plc', 1, ''),
(5, 'AIG', 'American International Group Inc.', 1, 'Vyradit kvuli spatne performance?'),
(6, 'ALL', 'Allstate Corp.', 1, ''),
(7, 'AMGN', 'Amgen Inc.', 1, ''),
(8, 'AMZN', 'Amazon.com', 1, ''),
(11, 'AXP', 'American Express Inc.', 1, ''),
(12, 'BA', 'Boeing Co.', 1, ''),
(13, 'BAC', 'Bank of America Corp', 1, ''),
(15, 'BIIB', 'Biogen Idec', 1, ''),
(16, 'BK', 'Bank of New York', 1, ''),
(17, 'BMY', 'Bristol-Myers Squibb', 1, ''),
(18, 'BRK-B', 'Berkshire Hathaway', 1, ''),
(19, 'C', 'Citigroup Inc', 1, ''),
(20, 'CAT', 'Caterpillar Inc', 1, ''),
(21, 'CL', 'Colgate-Palmolive Co.', 1, ''),
(22, 'CMCSA', 'Comcast Corporation', 1, ''),
(23, 'COF', 'Capital One Financial Corp.', 1, ''),
(24, 'COP', 'ConocoPhillips', 1, ''),
(25, 'COST', 'Costco', 1, ''),
(26, 'CSCO', 'Cisco Systems', 1, ''),
(27, 'CVS', 'CVS Caremark', 1, ''),
(28, 'CVX', 'Chevron', 1, ''),
(29, 'DD', 'DuPont', 1, ''),
(30, 'DIS', 'The Walt Disney Company', 1, ''),
(31, 'DOW', 'Dow Chemical', 1, ''),
(33, 'EBAY', 'eBay Inc.', 1, ''),
(35, 'EMR', 'Emerson Electric Co.', 1, ''),
(36, 'EXC', 'Exelon', 1, ''),
(37, 'F', 'Ford Motor', 1, ''),
(38, 'FB', 'Facebook', 1, ''),
(40, 'FDX', 'FedEx', 1, ''),
(41, 'FOXA', 'Twenty-First Century Fox, Inc', 1, ''),
(42, 'GD', 'General Dynamics', 1, ''),
(43, 'GE', 'General Electric Co.', 1, ''),
(44, 'GILD', 'Gilead Sciences', 1, ''),
(45, 'GM', 'General Motors', 1, ''),
(46, 'GOOG', 'Google Inc.', 1, ''),
(47, 'GS', 'Goldman Sachs', 1, ''),
(48, 'HAL', 'Halliburton', 1, ''),
(49, 'HD', 'Home Depot', 1, ''),
(50, 'HON', 'Honeywell', 1, ''),
(51, 'HPQ', 'Hewlett Packard Co', 1, ''),
(52, 'IBM', 'International Business Machines', 1, ''),
(53, 'JNJ', 'Johnson & Johnson Inc', 1, ''),
(54, 'JPM', 'JP Morgan Chase & Co', 1, ''),
(55, 'KO', 'The Coca-Cola Company', 1, ''),
(56, 'LLY', 'Eli Lilly and Company', 1, ''),
(57, 'LMT', 'Lockheed-Martin', 1, ''),
(58, 'LOW', 'Lowe\'s', 1, ''),
(59, 'MA', 'Mastercard Inc', 1, ''),
(60, 'INTC', 'Intel Corporation', 1, ''),
(61, 'MCD', 'McDonald\'s Corp', 1, ''),
(62, 'MDLZ', 'Mondelēz International', 1, ''),
(63, 'MDT', 'Medtronic Inc.', 1, ''),
(64, 'MET', 'Metlife Inc.', 1, ''),
(65, 'MMM', '3M Company', 1, ''),
(66, 'MO', 'Altria Group', 1, ''),
(67, 'MON', 'Monsanto', 1, ''),
(68, 'MRK', 'Merck & Co.', 1, ''),
(69, 'MS', 'Morgan Stanley', 1, ''),
(70, 'MSFT', 'Microsoft', 1, ''),
(71, 'NKE', 'Nike', 1, ''),
(74, 'ORCL', 'Oracle Corporation', 1, ''),
(75, 'OXY', 'Occidental Petroleum Corp.', 1, ''),
(76, 'PEP', 'Pepsico Inc.', 1, ''),
(77, 'PFE', 'Pfizer Inc', 1, ''),
(78, 'PG', 'Procter & Gamble Co', 1, ''),
(79, 'PM', 'Phillip Morris International', 1, ''),
(80, 'QCOM', 'Qualcomm Inc.', 1, ''),
(81, 'RTN', 'Raytheon Co (NEW)', 1, ''),
(82, 'SBUX', 'Starbucks Corporation', 1, ''),
(83, 'SLB', 'Schlumberger', 1, ''),
(84, 'SO', 'Southern Company', 1, ''),
(85, 'SPG', 'Simon Property Group, Inc.', 1, ''),
(86, 'T', 'AT&T Inc', 1, ''),
(87, 'TGT', 'Target Corp.', 1, ''),
(88, 'TWX', 'Time Warner Inc.', 1, ''),
(89, 'TXN', 'Texas Instruments', 1, ''),
(90, 'UNH', 'UnitedHealth Group Inc.', 1, ''),
(91, 'UNP', 'Union Pacific Corp.', 1, ''),
(92, 'UPS', 'United Parcel Service Inc', 1, ''),
(93, 'USB', 'US Bancorp', 1, ''),
(94, 'UTX', 'United Technologies Corp', 1, ''),
(95, 'V', 'Visa Inc.', 1, ''),
(96, 'VZ', 'Verizon Communications Inc', 1, ''),
(97, 'WFC', 'Wells Fargo', 1, ''),
(98, 'WMT', 'Wal-Mart', 1, ''),
(99, 'XOM', 'Exxon Mobil Corp', 1, ''),
(100, 'WBA', 'Walgreens Boots Alliance', 1, ''),
(601, 'AAPL', 'Apple Inc.', 1, ''),
(602, 'ABBV', 'AbbVie Inc.', 1, ''),
(603, 'TSLA', 'Tesla Motors, Inc.', 0, ''),
(604, 'AGN', 'ALLERGAN', 1, ''),
(605, 'PYPL', 'PAYPAL HOLDINGS INC', 1, ''),
(606, 'PCLN', 'PRICELINE GROUP INC/THE', 1, ''),
(607, 'NEE', 'NEXTERA ENERGY INC', 1, ''),
(608, 'KMI', 'KINDER MORGAN INC', 1, ''),
(609, 'KHC', 'KRAFT HEINZ', 1, ''),
(610, 'DUK', 'DUKE ENERGY CORP', 1, ''),
(611, 'DHR', 'DANAHER CORP', 1, ''),
(612, 'CELG', 'CELGENE CORP', 1, ''),
(613, 'BLK', 'BLACKROCK INC.', 1, '');
